#!/bin/bash
# Submit one SLURM pipeline job per dataset.
# Each job runs: Dorado basecalling → Remora refinement → Featurization.
# Results go to /fs/cbcb-scratch/bds062/results/benchmark_results/<DATASET>/
#
# Featurization requires GT_BED (orthogonal ground truth).  Run GT extraction
# first (extract_gt_emseq.sh / motif_gt.py), then set the GT paths below.
# Jobs skip featurization with a warning if GT_BED is absent.
#
# Usage: bash submit_all.sh [--dry-run] [dataset1 dataset2 ...]
# With no dataset args, submits all 13 datasets.

set -euo pipefail

SCRIPT=/fs/cbcb-scratch/bds062/scripts/pipeline.sh

BENCHREF=/fs/cbcb-scratch/bds062/data/benchmark/references
BENCHBACT=/fs/cbcb-scratch/bds062/data/benchmark/bacteria
BENCHDATA=/fs/cbcb-scratch/bds062/data/benchmark
HUMANDATA=/fs/cbcb-scratch/bds062/data/human
HUMANREF=${HUMANDATA}/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bgz

# Ground-truth BED root — generated by extract_gt_emseq.sh and motif_gt.py
GTROOT=/fs/cbcb-scratch/bds062/data/gt

# Motif GT (already generated by motif_gt.py — directory names are lowercase,
# independent of the Title_Case dataset names used below).
ANABAENA_GT="${GTROOT}/anabaena/gt_modified.bed";       ANABAENA_CAND="${GTROOT}/anabaena/candidate.bed"
HP26695_GT="${GTROOT}/hpylori_26695/gt_modified.bed";    HP26695_CAND="${GTROOT}/hpylori_26695/candidate.bed"
HPJ99_GT="${GTROOT}/hpylori_j99/gt_modified.bed";        HPJ99_CAND="${GTROOT}/hpylori_j99/candidate.bed"
TDENT_GT="${GTROOT}/tdenticola/gt_modified.bed";         TDENT_CAND="${GTROOT}/tdenticola/candidate.bed"

# Bisulfite/WGBS GT (generated by extract_gt_bismark.py / extract_gt_from_pileup.py —
# empty string until the corresponding job has been run and produced output).
ARAB_GT="${GTROOT}/arabidopsis/gt_modified.bed";         ARAB_CAND="${GTROOT}/arabidopsis/candidate.bed"
OSATIVA_GT="${GTROOT}/osativa/gt_modified.bed";          OSATIVA_CAND="${GTROOT}/osativa/candidate.bed"
HG001_GT="${GTROOT}/hg001/gt_modified.bed";               HG001_CAND="${GTROOT}/hg001/candidate.bed"
HG002_GT="${GTROOT}/hg002/gt_modified.bed";               HG002_CAND="${GTROOT}/hg002/candidate.bed"
# Mouse emseq_bam download failed (0 bytes) — no GT source yet.
MOUSE_GT="";                                              MOUSE_CAND=""

DRY_RUN=false
FILTER=()

for arg in "$@"; do
    if [[ "$arg" == "--dry-run" ]]; then
        DRY_RUN=true
    else
        FILTER+=("$arg")
    fi
done

# submit dataset pod5_dir ref gt_bed candidate_bed qos time_limit recursive min_reads
submit() {
    local dataset="$1"
    local pod5_dir="$2"
    local ref="$3"
    local gt_bed="${4:-}"
    local candidate_bed="${5:-}"
    local qos="${6:-high}"
    local time_limit="${7:-24:00:00}"
    local recursive="${8:-false}"
    local min_reads="${9:-25}"

    if [[ ${#FILTER[@]} -gt 0 ]]; then
        local match=false
        for f in "${FILTER[@]}"; do
            [[ "$f" == "$dataset" ]] && match=true && break
        done
        $match || return 0
    fi

    if [[ ! -d "$pod5_dir" ]]; then
        echo "[SKIP] $dataset — pod5 dir not found: $pod5_dir"
        return 0
    fi

    local mem="128G"
    [[ "${qos}" == "highmem" ]] && mem="256G"

    local export_args="DATASET=${dataset},POD5_DIR=${pod5_dir},REF=${ref},RECURSIVE=${recursive},MIN_READS=${min_reads}"
    [[ -n "$gt_bed" ]]       && export_args+=",GT_BED=${gt_bed}"
    [[ -n "$candidate_bed" ]] && export_args+=",CANDIDATE_BED=${candidate_bed}"

    if $DRY_RUN; then
        echo "[dry-run] sbatch --job-name=${dataset} --qos=${qos} --mem=${mem} --time=${time_limit} --export=${export_args} ${SCRIPT}"
    else
        local job_id
        job_id=$(sbatch --job-name="${dataset}" \
                        --qos="${qos}" \
                        --mem="${mem}" \
                        --time="${time_limit}" \
                        --export="${export_args}" \
                        "${SCRIPT}" \
                    | awk '{print $NF}')
        echo "[submitted] ${dataset} → job ${job_id}"
    fi
}

# ── GT BED paths ─────────────────────────────────────────────────────────────
# Motif-based (pre-generated, immediately available):
#   python /fs/cbcb-scratch/bds062/scripts/motif_gt.py --ref REF --preset PRESET --outdir GTROOT/NAME
#
# Emseq-based (requires emseq BAM download + modkit job):
#   sbatch /fs/cbcb-scratch/bds062/scripts/extract_gt_emseq.sh
#   with DATASET, EMSEQ_BAM, REF, OUTDIR exported
#
# Featurization is SKIPPED (with a warning) if GT_BED does not exist yet.
# Re-run submit_all.sh once GT files are ready.

# ── Human ──────────────────────────────────────────────────────────────────────
submit hg001 \
    "${HUMANDATA}/hg001/pod5" \
    "${HUMANREF}" \
    "${HG001_GT}" \
    "${HG001_CAND}" \
    highmem "72:00:00" \
    true 5   # recursive pod5; min_reads=5 (low coverage)

submit hg002 \
    "${HUMANDATA}/hg002/pod5" \
    "${HUMANREF}" \
    "${HG002_GT}" \
    "${HG002_CAND}" \
    highmem "72:00:00" \
    true 5

# ── Bacteria ───────────────────────────────────────────────────────────────────
# Anabaena WT: Dam-like 6mA at GATC
submit Anabaena_WT_5kHz \
    "${BENCHBACT}/Anabaena_WT_5kHz/pod5" \
    "${BENCHREF}/anabaena_sp_PCC7120_ATCC27893.fa.gz" \
    "${ANABAENA_GT}" \
    "${ANABAENA_CAND}"

# E. coli DM: Dam (6mA at GATC) only
submit Ecoli_DM_5kHz \
    "${BENCHBACT}/Ecoli_DM_5kHz/pod5" \
    "${BENCHREF}/ecoli.fa.gz" \
    "${GTROOT}/Ecoli_DM/gt_modified.bed" \
    "${GTROOT}/Ecoli_DM/candidate.bed"

# E. coli DM + MSssI: Dam (6mA at GATC) + MSssI (5mC at all CG) — combined GT
submit Ecoli_DM_MSssI_5kHz \
    "${BENCHBACT}/Ecoli_DM_MSssI_5kHz/pod5" \
    "${BENCHREF}/ecoli.fa.gz" \
    "${GTROOT}/Ecoli_DM_MSssI/gt_modified.bed" \
    "${GTROOT}/Ecoli_DM_MSssI/candidate.bed"

# E. coli WT: Dam (6mA at GATC) + Dcm (5mC at CCWGG) — combined GT
submit Ecoli_WT_5kHz \
    "${BENCHBACT}/Ecoli_WT_5kHz/pod5" \
    "${BENCHREF}/ecoli.fa.gz" \
    "${GTROOT}/Ecoli_WT/gt_modified.bed" \
    "${GTROOT}/Ecoli_WT/candidate.bed"

# H. pylori WGA: whole-genome amplified = NO modifications.
# Pass an empty BED as GT → all labels=0 (pure unmodified signal control).
# An empty file is valid: load_gt() returns an empty set, all images get label=0.
WGA_EMPTY_GT="${GTROOT}/empty.bed"
mkdir -p "${GTROOT}" && touch "${WGA_EMPTY_GT}"

submit HP26695_WGA_5kHz \
    "${BENCHBACT}/HP26695_WGA_5kHz/pod5" \
    "${BENCHREF}/hpylori_26695.fa.gz" \
    "${WGA_EMPTY_GT}" "" \
    high "24:00:00"

submit HP26695_WT_5kHz \
    "${BENCHBACT}/HP26695_WT_5kHz/pod5" \
    "${BENCHREF}/hpylori_26695.fa.gz" \
    "${HP26695_GT}" \
    "${HP26695_CAND}"

submit HPJ99_WT_5kHz \
    "${BENCHBACT}/HPJ99_WT_5kHz/pod5" \
    "${BENCHREF}/hpylori_J99_ATCC700824.fa.gz" \
    "${HPJ99_GT}" \
    "${HPJ99_CAND}"

submit Tdenticola_WT_5kHz \
    "${BENCHBACT}/Tdenticola_WT_5kHz/pod5" \
    "${BENCHREF}/treponema_denticola_ATCC35405.fa.gz" \
    "${TDENT_GT}" \
    "${TDENT_CAND}"

# ── Plants ─────────────────────────────────────────────────────────────────────
submit arabidopsis \
    "${BENCHDATA}/arabidopsis/pod5" \
    "${BENCHREF}/arabidopsis_thaliana.fa.gz" \
    "${ARAB_GT}" \
    "${ARAB_CAND}" \
    highmem "72:00:00"

submit osativa \
    "${BENCHDATA}/osativa/pod5" \
    "${BENCHREF}/oryza_sativa_japonica.fa.gz" \
    "${OSATIVA_GT}" \
    "${OSATIVA_CAND}" \
    highmem "72:00:00"

# ── Mouse ───────────────────────────────────────────────────────────────────────
submit mouse \
    "${BENCHDATA}/mouse/pod5" \
    "${BENCHREF}/mouse_mm39.fa.gz" \
    "${MOUSE_GT}" \
    "${MOUSE_CAND}" \
    highmem "72:00:00" \
    false 5   # min_reads=5 (low coverage ~5x)
